# Changes here will be overwritten by Copier
_commit: 1.0.8
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2018'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC License
insiders: false
project_description: Translate ANSI codes to any other format.
project_name: ansito
python_package_command_line_name: ansito
python_package_distribution_name: ansito
python_package_import_name: ansito
repository_name: ansito
repository_namespace: pawamoy
repository_provider: github.com

